# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name=b'First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name=b'Last Name')),
                ('email', models.EmailField(max_length=255, verbose_name=b'Email')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name=b'Phone number')),
                ('country', models.CharField(max_length=255, verbose_name=b'Country')),
                ('date_inquired', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Date Inquired')),
                ('name', models.CharField(max_length=255, verbose_name=b'Health Care Facility Name')),
                ('district', models.CharField(max_length=255, verbose_name=b'District')),
                ('accreditation', models.CharField(max_length=255, verbose_name=b'Accreditation Code')),
                ('level', models.CharField(choices=[(b'', b'Level of health care provided'), (b'A', b'A'), (b'B1', b'B1'), (b'B2', b'B2'), (b'M', b'M'), (b'C', b'C'), (b'D', b'D'), (b'E', b'E')], max_length=255, verbose_name=b'Level')),
            ],
            options={
                'verbose_name': 'Registration',
                'verbose_name_plural': 'Registrations',
            },
        ),
    ]
