# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 18:05
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20160413_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='claimProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffID', models.CharField(max_length=255, verbose_name='Staff ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('email', models.EmailField(default='info@info.com', max_length=255, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, default='0240647463', max_length=30, verbose_name='Phone number')),
                ('country', models.CharField(default='Ghana', max_length=255, verbose_name='location')),
                ('date_inquired', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Inquired')),
                ('district', models.CharField(default='JIRAPA-LAMBUSSIE', max_length=255, verbose_name='District')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Claim Manager Profile',
                'verbose_name_plural': 'Claim Manager Profiles',
            },
        ),
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('email', models.EmailField(default='info@info.com', max_length=255, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, default='0240647463', max_length=30, verbose_name='Phone number')),
                ('country', models.CharField(default='Ghana', max_length=255, verbose_name='location')),
                ('date_inquired', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Inquired')),
                ('name', models.CharField(max_length=255, verbose_name='Health Care Facility Name')),
                ('district', models.CharField(default='JIRAPA-LAMBUSSIE', max_length=255, verbose_name='District')),
                ('accreditation', models.CharField(max_length=255, verbose_name='Accreditation Code')),
                ('level', models.CharField(choices=[('', '---Level of health care provided--'), ('A', 'Chips compound'), ('B1', 'Health Centre without a Doctor'), ('B2', 'Health centre with a Doctor'), ('M', 'Maternity home with Midwife'), ('C', 'District Hospital'), ('D', 'Regional Hospital'), ('E', 'Teaching Hospital')], max_length=255, verbose_name='Provider Type')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Health Care Professional Profiles',
                'verbose_name_plural': 'Health Care Professional Profiles',
            },
        ),
        migrations.RemoveField(
            model_name='registration',
            name='owner',
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterField(
            model_name='claim',
            name='ClaimNumber',
            field=models.CharField(blank=True, max_length=255, verbose_name='Claim Number'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='Client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Patient', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='DateofClaim',
            field=models.DateField(blank=True, verbose_name='Date of Claim'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='GDRGFourdiag',
            field=models.CharField(blank=True, choices=[('', 'Diagnosis G-DRG'), ('ASUR01', 'ASUR01'), ('ASUR02', 'ASUR02'), ('ASUR03', 'ASUR03'), ('ASUR04', 'ASUR04'), ('ASUR05', 'ASUR05')], max_length=255, verbose_name='G-DRG diagnosis 4'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='GDRGOnediag',
            field=models.CharField(blank=True, choices=[('', 'Diagnosis G-DRG'), ('ASUR01', 'ASUR01'), ('ASUR02', 'ASUR02'), ('ASUR03', 'ASUR03'), ('ASUR04', 'ASUR04'), ('ASUR05', 'ASUR05')], max_length=255, verbose_name='G-DRG diagnosis 1'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='GDRGOneprocedure',
            field=models.CharField(blank=True, choices=[('', '--Procedure Description--'), ('None', 'None')], max_length=255, verbose_name='G-DRG Procedure 1'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='GDRGThreediag',
            field=models.CharField(blank=True, choices=[('', 'Diagnosis G-DRG'), ('ASUR01', 'ASUR01'), ('ASUR02', 'ASUR02'), ('ASUR03', 'ASUR03'), ('ASUR04', 'ASUR04'), ('ASUR05', 'ASUR05')], max_length=255, verbose_name='G-DRG diagnosis 3'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='GDRGThreeprocedure',
            field=models.CharField(blank=True, choices=[('', '--Procedure Description--'), ('None', 'None')], max_length=255, verbose_name='G-DRG Procedure 3'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='GDRGTwodiag',
            field=models.CharField(blank=True, choices=[('', 'Diagnosis G-DRG'), ('ASUR01', 'ASUR01'), ('ASUR02', 'ASUR02'), ('ASUR03', 'ASUR03'), ('ASUR04', 'ASUR04'), ('ASUR05', 'ASUR05')], max_length=255, verbose_name='G-DRG diagnosis 2'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='GDRGTwoprocedure',
            field=models.CharField(blank=True, choices=[('', '--Procedure Description--'), ('None', 'None')], max_length=255, verbose_name='G-DRG Procedure 2'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='Pharamacy',
            field=models.BooleanField(default=False, verbose_name='Pharamacy'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='attendance',
            field=models.CharField(blank=True, choices=[('', '--Attendance--'), ('Chronic Follow-Up', 'Chronic Follow-Up'), ('Emgergency/Acute episode', 'Emgergency/Acute episode')], max_length=255, verbose_name='Type of Attendance'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='diagFourDescription',
            field=models.CharField(blank=True, choices=[('', 'Diagnosis Description'), ('None', 'None')], max_length=255, verbose_name='diagnosis 4 Description'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='diagFour_date',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='diagnosis 4 Date'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='diagOneDescription',
            field=models.CharField(blank=True, choices=[('', 'Diagnosis Description'), ('None', 'None')], max_length=255, verbose_name='diagnosis 1 Description'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='diagOne_date',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='diagnosis 1 Date'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='diagThreeDescription',
            field=models.CharField(blank=True, choices=[('', 'Diagnosis Description'), ('None', 'None')], max_length=255, verbose_name='diagnosis 3 Description'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='diagThree_date',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='diagnosis 3 Date'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='diagTwoDescription',
            field=models.CharField(blank=True, choices=[('', 'Diagnosis Description'), ('None', 'None')], max_length=255, verbose_name='diagnosis 2 Description'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='diagTwo_date',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='diagnosis 2 Date'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='durationDays',
            field=models.IntegerField(blank=True, default=0, max_length=30, verbose_name='Duration of Spell (Days)'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='first_visit_date',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='First Visit Date'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='forth_visit_date',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='Fourth Visit Date'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medCodeFive',
            field=models.CharField(blank=True, max_length=255, verbose_name='Medicine Code 5'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medCodeFour',
            field=models.CharField(blank=True, max_length=255, verbose_name='Medicine Code 4'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medCodeOne',
            field=models.CharField(blank=True, max_length=255, verbose_name='Medicine Code 1'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medCodeThree',
            field=models.CharField(blank=True, max_length=255, verbose_name='Medicine Code 3'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medCodeTwo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Medicine Code 2'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medFiveDescription',
            field=models.CharField(blank=True, choices=[('', '--Medicine Code--'), ('ACETAZIN1', 'ACETAZIN1'), ('ACETAZTA1', 'ACETAZTA1'), ('ACETYLIN1', 'ACETYLIN1'), ('ACETYLTA1', 'ACETYLTA1'), ('ACETYLDT1', 'ACETYLDT1'), ('ACTCHAPO1', 'ACTCHAPO1'), ('ACICLOCR1', 'ACICLOCR1'), ('ACICLOEO1', 'ACICLOEO1'), ('ACICLOIN1', 'ACICLOIN1'), ('ACICLOSU2', 'ACICLOSU2'), ('ACICLOTA1', 'ACICLOTA1'), ('ADRENAIN1', 'ADRENAIN1'), ('ADRENAIN2', 'ADRENAIN2'), ('ADRIAMIN1', 'ADRIAMIN1'), ('ALBENDTA1', 'ALBENDTA1'), ('ALBENDTA2', 'ALBENDTA2'), ('ALLOPUTA1', 'ALLOPUTA1'), ('ALLOPUTA2', 'ALLOPUTA2'), ('AMIACIIN1', 'AMIACIIN1')], max_length=255, verbose_name='Medicine 5 Description'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medFivePrice',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=20, verbose_name='Medicine Five Price'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medFiveTotal',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=20, verbose_name='Medicine Five Total Cost'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medFive_date',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='Medicine 5 Date'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medFourDescription',
            field=models.CharField(blank=True, choices=[('', '--Medicine Code--'), ('ACETAZIN1', 'ACETAZIN1'), ('ACETAZTA1', 'ACETAZTA1'), ('ACETYLIN1', 'ACETYLIN1'), ('ACETYLTA1', 'ACETYLTA1'), ('ACETYLDT1', 'ACETYLDT1'), ('ACTCHAPO1', 'ACTCHAPO1'), ('ACICLOCR1', 'ACICLOCR1'), ('ACICLOEO1', 'ACICLOEO1'), ('ACICLOIN1', 'ACICLOIN1'), ('ACICLOSU2', 'ACICLOSU2'), ('ACICLOTA1', 'ACICLOTA1'), ('ADRENAIN1', 'ADRENAIN1'), ('ADRENAIN2', 'ADRENAIN2'), ('ADRIAMIN1', 'ADRIAMIN1'), ('ALBENDTA1', 'ALBENDTA1'), ('ALBENDTA2', 'ALBENDTA2'), ('ALLOPUTA1', 'ALLOPUTA1'), ('ALLOPUTA2', 'ALLOPUTA2'), ('AMIACIIN1', 'AMIACIIN1')], max_length=255, verbose_name='Medicine 4 Description'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medFourPrice',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=20, verbose_name='Medicine Four Price'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medFourTotal',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=20, verbose_name='Medicine Four Total Cost'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medFour_date',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='Medicine 4 Date'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medOneDescription',
            field=models.CharField(blank=True, choices=[('', '--Medicine Code--'), ('ACETAZIN1', 'ACETAZIN1'), ('ACETAZTA1', 'ACETAZTA1'), ('ACETYLIN1', 'ACETYLIN1'), ('ACETYLTA1', 'ACETYLTA1'), ('ACETYLDT1', 'ACETYLDT1'), ('ACTCHAPO1', 'ACTCHAPO1'), ('ACICLOCR1', 'ACICLOCR1'), ('ACICLOEO1', 'ACICLOEO1'), ('ACICLOIN1', 'ACICLOIN1'), ('ACICLOSU2', 'ACICLOSU2'), ('ACICLOTA1', 'ACICLOTA1'), ('ADRENAIN1', 'ADRENAIN1'), ('ADRENAIN2', 'ADRENAIN2'), ('ADRIAMIN1', 'ADRIAMIN1'), ('ALBENDTA1', 'ALBENDTA1'), ('ALBENDTA2', 'ALBENDTA2'), ('ALLOPUTA1', 'ALLOPUTA1'), ('ALLOPUTA2', 'ALLOPUTA2'), ('AMIACIIN1', 'AMIACIIN1')], max_length=255, verbose_name='Medicine 1 Description'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medOnePrice',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=20, verbose_name='Medicine One Price'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medOneTotal',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=20, verbose_name='Medicine One Total Cost'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medOne_date',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='Medicine 1 Date'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medQTYFive',
            field=models.IntegerField(blank=True, default=0, verbose_name='Medicine 5 Quantity'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medQTYFour',
            field=models.IntegerField(blank=True, default=0, verbose_name='Medicine 4 Quantity'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medQTYThree',
            field=models.IntegerField(blank=True, default=0, verbose_name='Medicine 3 Quantity'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medQTYTwo',
            field=models.IntegerField(blank=True, default=0, verbose_name='Medicine 2 Quantity'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medQTYone',
            field=models.IntegerField(blank=True, default=0, verbose_name='Medicine 1 Quantity'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medThreeDescription',
            field=models.CharField(blank=True, choices=[('', '--Medicine Code--'), ('ACETAZIN1', 'ACETAZIN1'), ('ACETAZTA1', 'ACETAZTA1'), ('ACETYLIN1', 'ACETYLIN1'), ('ACETYLTA1', 'ACETYLTA1'), ('ACETYLDT1', 'ACETYLDT1'), ('ACTCHAPO1', 'ACTCHAPO1'), ('ACICLOCR1', 'ACICLOCR1'), ('ACICLOEO1', 'ACICLOEO1'), ('ACICLOIN1', 'ACICLOIN1'), ('ACICLOSU2', 'ACICLOSU2'), ('ACICLOTA1', 'ACICLOTA1'), ('ADRENAIN1', 'ADRENAIN1'), ('ADRENAIN2', 'ADRENAIN2'), ('ADRIAMIN1', 'ADRIAMIN1'), ('ALBENDTA1', 'ALBENDTA1'), ('ALBENDTA2', 'ALBENDTA2'), ('ALLOPUTA1', 'ALLOPUTA1'), ('ALLOPUTA2', 'ALLOPUTA2'), ('AMIACIIN1', 'AMIACIIN1')], max_length=255, verbose_name='Medicine 3 Description'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medThreePrice',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=20, verbose_name='Medicine Three Price'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medThreeTotal',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=20, verbose_name='Medicine Three Total Cost'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medThree_date',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='Medicine 3 Date'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medTwoDescription',
            field=models.CharField(blank=True, choices=[('', '--Medicine Code--'), ('ACETAZIN1', 'ACETAZIN1'), ('ACETAZTA1', 'ACETAZTA1'), ('ACETYLIN1', 'ACETYLIN1'), ('ACETYLTA1', 'ACETYLTA1'), ('ACETYLDT1', 'ACETYLDT1'), ('ACTCHAPO1', 'ACTCHAPO1'), ('ACICLOCR1', 'ACICLOCR1'), ('ACICLOEO1', 'ACICLOEO1'), ('ACICLOIN1', 'ACICLOIN1'), ('ACICLOSU2', 'ACICLOSU2'), ('ACICLOTA1', 'ACICLOTA1'), ('ADRENAIN1', 'ADRENAIN1'), ('ADRENAIN2', 'ADRENAIN2'), ('ADRIAMIN1', 'ADRIAMIN1'), ('ALBENDTA1', 'ALBENDTA1'), ('ALBENDTA2', 'ALBENDTA2'), ('ALLOPUTA1', 'ALLOPUTA1'), ('ALLOPUTA2', 'ALLOPUTA2'), ('AMIACIIN1', 'AMIACIIN1')], max_length=255, verbose_name='Medicine 2 Description'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medTwoPrice',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=20, verbose_name='riMedicine Two Price'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medTwoTotal',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=20, verbose_name='riMedicine Two Total Cost'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medTwo_date',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='Medicine 2 Date'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='outcome',
            field=models.CharField(blank=True, choices=[('', '--Outcome--'), ('Discharged', 'Discharged'), ('Died', 'Died'), ('Transferred Out', 'Transferred Out'), ('Absconded', 'Absconded')], max_length=255, verbose_name='Outcome'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='procedureOneDescription',
            field=models.CharField(blank=True, choices=[('', '--Procedure Description--'), ('None', 'None')], max_length=255, verbose_name='Precedure 1 Description'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='procedureOne_date',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='Procedure 1 Date'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='procedureThreeDescription',
            field=models.CharField(blank=True, choices=[('', '--Procedure Description--'), ('None', 'None')], max_length=255, verbose_name='Precedure 3 Description'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='procedureThree_date',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='Procedure 3 Date'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='procedureTwoDescription',
            field=models.CharField(blank=True, choices=[('', '--Procedure Description--'), ('None', 'None')], max_length=255, verbose_name='Precedure 2 Description'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='procedureTwo_date',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='Procedure 2 Date'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='scheme_name',
            field=models.CharField(blank=True, default='JIRAPA DISTRICT NHIS', max_length=255, verbose_name='Scheme Name'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='second_visit_date',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='Second Visit Date'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='specialtyCode',
            field=models.CharField(blank=True, max_length=4, verbose_name='Specialty Code'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='specialtyDescription',
            field=models.CharField(blank=True, max_length=255, verbose_name='Specialty Description'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='third_visit_date',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='Third Visit Date'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='typeOfService',
            field=models.CharField(blank=True, choices=[('', '--Service--'), ('Outpatient', 'Outpatient'), ('Diagnostic', 'Diagnostic'), ('In-Patient', 'In-Patient'), ('All Inclusive', 'All Inclusive'), ('Unbundled', 'Unbundled')], max_length=255, verbose_name='Type of service (i)'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='Code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='Price',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=20, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='Price_Unit',
            field=models.CharField(blank=True, max_length=255, verbose_name='Price Unit'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Generic Name'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='level',
            field=models.CharField(blank=True, choices=[('', '---Level of health care provided--'), ('A', 'Chips compound'), ('B1', 'Health Centre without a Doctor'), ('B2', 'Health centre with a Doctor'), ('M', 'Maternity home with Midwife'), ('C', 'District Hospital'), ('D', 'Regional Hospital'), ('E', 'Teaching Hospital')], max_length=255, verbose_name='Level of prescribing'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Age',
            field=models.IntegerField(blank=True, default=18, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthdate',
            field=models.DateField(blank=True, verbose_name='Birthdate'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('', '--Gender--'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=255, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospital_record_number',
            field=models.CharField(blank=True, default='0000000', max_length=255, verbose_name='Hospital Record No:'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nhis_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='NHIS Number'),
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
