# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160530_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birthdate',
            field=models.DateField(blank=True, verbose_name='Expiry Date'),
        ),
    ]
