# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 18:30
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160530_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='attendance',
            field=models.CharField(blank=True, choices=[('', '--Attendance--'), ('Chronic Follow-Up', 'Chronic Follow-Up'), ('Emgergency', 'Emgergency'), ('Acute episode', 'Acute episode')], max_length=255, verbose_name='Type of Attendance'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medFiveDescription',
            field=models.CharField(blank=True, max_length=255, verbose_name='Medicine 5 Description'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medFivePrice',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.00'), max_digits=20, verbose_name='Medicine 5 Price'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medFiveTotal',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.00'), max_digits=20, verbose_name='Medicine 4 Total Cost'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medFourDescription',
            field=models.CharField(blank=True, max_length=255, verbose_name='Medicine 4 Description'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medFourPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Medicine 4 Price'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medFourTotal',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.00'), max_digits=20, verbose_name='Medicine 4 Total Cost'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medOneDescription',
            field=models.CharField(blank=True, max_length=255, verbose_name='Medicine 1 Description'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medOnePrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Medicine 1 Price'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medOneTotal',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.00'), max_digits=20, verbose_name='Medicine 1 Total Cost'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medThreeDescription',
            field=models.CharField(blank=True, max_length=255, verbose_name='Medicine 3 Description'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medThreePrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Medicine 3 Price'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medThreeTotal',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.00'), max_digits=20, verbose_name='Medicine 3 Total Cost'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medTwoDescription',
            field=models.CharField(blank=True, max_length=255, verbose_name='Medicine 2 Description'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medTwoPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Medicine 2 Price'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medTwoTotal',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.00'), max_digits=20, verbose_name='Medicine 2 Total Cost'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='outcome',
            field=models.CharField(blank=True, choices=[('', '--Outcome--'), ('Discharged', 'Discharged'), ('Discharged Against Medical advice', 'Discharged Against Medical advice'), ('Died', 'Died'), ('Transferred Out', 'Transferred Out'), ('Absconded', 'Absconded')], max_length=255, verbose_name='Outcome'),
        ),
    ]
