# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 19:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160601_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='clientNHISNumber',
            field=models.DateField(default=datetime.datetime(2016, 6, 1, 19, 56, 16, 99533, tzinfo=utc), verbose_name='Client NHIS number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='Client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Patient', verbose_name='Client'),
        ),
    ]
