# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20160601_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='all_inclusive',
            field=models.BooleanField(default=False, verbose_name='All Inclusive'),
        ),
        migrations.AddField(
            model_name='claim',
            name='unbundled',
            field=models.BooleanField(default=False, verbose_name='Unbundled'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='Client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Patient', verbose_name='Client'),
        ),
    ]
