# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20160601_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='GDRGFourdiag',
            field=models.CharField(blank=True, max_length=255, verbose_name='G-DRG diagnosis 4'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='GDRGOnediag',
            field=models.CharField(blank=True, max_length=255, verbose_name='G-DRG diagnosis 1'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='GDRGOneprocedure',
            field=models.CharField(blank=True, max_length=255, verbose_name='G-DRG Procedure 1'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='GDRGThreediag',
            field=models.CharField(blank=True, max_length=255, verbose_name='G-DRG diagnosis 3'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='GDRGThreeprocedure',
            field=models.CharField(blank=True, max_length=255, verbose_name='G-DRG Procedure 3'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='GDRGTwodiag',
            field=models.CharField(blank=True, max_length=255, verbose_name='G-DRG diagnosis 2'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='GDRGTwoprocedure',
            field=models.CharField(blank=True, max_length=255, verbose_name='G-DRG Procedure 2'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='diagFourDescription',
            field=models.CharField(blank=True, max_length=255, verbose_name='diagnosis 4 Description'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='diagOneDescription',
            field=models.CharField(blank=True, max_length=255, verbose_name='diagnosis 1 Description'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='diagThreeDescription',
            field=models.CharField(blank=True, max_length=255, verbose_name='diagnosis 3 Description'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='diagTwoDescription',
            field=models.CharField(blank=True, max_length=255, verbose_name='diagnosis 2 Description'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='procedureOneDescription',
            field=models.CharField(blank=True, max_length=255, verbose_name='Precedure 1 Description'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='procedureThreeDescription',
            field=models.CharField(blank=True, max_length=255, verbose_name='Precedure 3 Description'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='procedureTwoDescription',
            field=models.CharField(blank=True, max_length=255, verbose_name='Precedure 2 Description'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='typeOfService',
            field=models.CharField(blank=True, choices=[('', '--Service--'), ('Outpatient', 'Outpatient'), ('Diagnostic', 'Diagnostic'), ('In-Patient', 'In-Patient')], max_length=255, verbose_name='Type of service (i)'),
        ),
    ]
