# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20160601_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code_gdrg', models.CharField(blank=True, max_length=255, verbose_name='Code')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name of Core Ghana Diagnosis (Grouping) ')),
                ('icd_ten', models.CharField(blank=True, max_length=255, verbose_name='ICD 10 Code')),
                ('detail', models.CharField(blank=True, max_length=255, verbose_name='Details of Diagnosis/Indication of procedures ')),
                ('level', models.CharField(blank=True, choices=[('', '---Level of health care provided--'), ('A', 'Chips compound'), ('B1', 'Health Centre without a Doctor'), ('B2', 'Health centre with a Doctor'), ('M', 'Maternity home with Midwife'), ('C', 'District Hospital'), ('D', 'Regional Hospital'), ('E', 'Teaching Hospital')], max_length=255, verbose_name='Level of prescribing')),
            ],
            options={
                'verbose_name_plural': 'Diagnosises',
                'verbose_name': 'Diagnosis',
            },
        ),
    ]
