# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='submitted_by',
            field=models.CharField(blank=True, max_length=255, verbose_name='Health Care Professional Name'),
        ),
    ]
